repos:
  -   repo: local
      hooks:
        -   id: dotnet-format-backend
            name: Format .NET Backend Code (C#)
            entry: ./scripts/dotnet_format.sh
            verbose: true
            language: system
            types: ["c#"] 